### ISSUE TITLE
Impossible to import : No such file or directory "VERSION"

### ISSUE THREAD

**Issue by yanjost** [mavier/jsobject#3]
Python 2.7.8 (virtualenv)

After installation, I try to import the module and get the following error

IOError: [Errno 2] No such file or directory: '/home/[redacted]/venv/local/lib/python2.7/site-packages/jsobject/../VERSION'

Installation log was :

[1] $ pip install jsobject                                                                                     
Downloading/unpacking jsobject
  Downloading jsobject-0.9.20.tar.gz
  Running setup.py (path:/home/[redacted]/venv/build/jsobject/setup.py) egg_info for package jsobject
    
Installing collected packages: jsobject
  Running setup.py install for jsobject
    warning: install_data: setup script did not provide a directory for 'VERSION' -- installing right in '/home/[redacted]/venv'
    
    
Successfully installed jsobject
Cleaning up...

**Comment by yanjost** [comment]
Thank you !

**Comment by mavier** [comment]
Welcome!
[New version 0.9.21!](https://pypi.python.org/pypi/jsobject/0.9.21)
